#!/usr/bin/env sh
# ------------------------------------------------------------------------------
# Gradle start up script for UN*X
#
# Generated by the Gradle wrapper when the wrapper task is run.
#
# This file may be used to invoke a Gradle build with the gradle wrapper.
#
# Usage: ./gradlew [args...]
#
# ----------------------------------------------------------------------------
set -e

DIRNAME="`dirname "$0"`"
APP_BASE_NAME="gradle"
APP_HOME="`cd "$DIRNAME" >/dev/null; pwd`"

LIBDIR="$APP_HOME/gradle/wrapper"

CLASSPATH="$LIBDIR/gradle-wrapper.jar"

# Determine Java command to use to run the JVM
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
fi

# Check whether the Java command exists
if [ ! -x "$JAVACMD" ] ; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." 1>&2
    exit 1
fi

# Use the maximum available, or set MAX_HEAP_SIZE env var
if [ -z "$MAX_HEAP_SIZE" ] ; then
    MAX_HEAP_SIZE="";
fi

# Execute Gradle
exec "$JAVACMD" $MAX_HEAP_SIZE -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@" 
