@echo off
::---------------------------------------------------------------------
:: Gradle startup script for Windows
::
:: Generated by the Gradle wrapper when the wrapper task is run.
::
:: This file may be used to invoke a Gradle build with the gradle wrapper.
::
:: Usage: gradlew.bat [args...]
::
::---------------------------------------------------------------------
@echo off
set DIRNAME=%~dp0nset APP_BASE_NAME=gradlenset APP_HOME=%DIRNAME:~0,-1%
set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
nif defined JAVA_HOME (
    if exist "%JAVA_HOME%\jre\bin\java.exe" (
        set "JAVACMD=%JAVA_HOME%\jre\bin\java.exe"
    ) else (
        set "JAVACMD=%JAVA_HOME%\bin\java.exe"
    )
) else (
    set "JAVACMD=java"
)
nif not exist "%JAVACMD%" (
    echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
    exit /b 1
)
n"%JAVACMD%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
